name: Django CI/CD Pipeline with Docker Compose
on:
  push:
    branches:
      - main
      - pre-release

  pull_request:
    branches:
      - main

  jobs:
    build:
      runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 8000:8000

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker compose -f docker-compose.yml up --build -d

      - name: Wait for Django app to be ready
        run: |
          for i in {1..10}; do
            if curl -s http://localhost:8000; then
              echo "Django app is up!"
              break
            fi
            echo "Waiting for Django app to be ready..."
            sleep 5
          done

      - name: Run tests
        run: |
          docker compose exec app python manage.py test

      - name: Stop Docker containers
        run: docker compose down
